### ISSUE TITLE
Page build failed

### ISSUE THREAD

**Issue by findsec-cn** [renzhaosy/hexo-deploy-action#1]
Deploy succeeded，but page build failed！

    name: GitHub Actions Build and Deploy Demo
    on:
      push:
        branches:
          - master
    jobs:
      build-and-deploy:
        runs-on: ubuntu-latest
        steps:
        - name: Checkout
          uses: actions/checkout@master
    
        - name: Build and Deploy
          uses: renzhaosy/hexo-deploy-action@master
          env:
            PERSONAL_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            PUBLISH_REPOSITORY: findsec-cn/github-actions-demo # The repository the action should deploy to.
            BRANCH: gh-pages  # The branch the action should deploy to.
            PUBLISH_DIR: ./public # The folder the action should deploy.

![build](https://user-images.githubusercontent.com/46661436/68911685-c630e680-0790-11ea-91d4-0edc22ec4692.jpg)

![build_faild](https://user-images.githubusercontent.com/46661436/68911700-ce892180-0790-11ea-9c73-8ab54c22f4b6.jpg)

**Comment by renzhaosy** [comment]
应该是 github 误认为网站是使用 Jekyll 构建的, gh-pages 分支下 ，增加 .nojekyll 文件禁用 Jekyll 检测。

**Comment by renzhaosy** [comment]
@findsec-cn   应该是 github 误认为网站是使用 Jekyll 构建的, gh-pages 分支下 ，增加 .nojekyll 文件禁用 Jekyll 检测。
